# Generated by Django 3.2.3 on 2021-05-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0002_stockhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
